[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defaultmap = "0.6.0"
memoize = "0.4.1"
regex = "1.10.2"
sscanf = "0.4.1"
